Distributed-Cw2/Controllers/CustomersController.cs
using Composite;
using Composite.Models.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System.Web;
using Braintree;
using Web.Models;
using Customer = Composite.Data.Customer;
using System.Diagnostics;

namespace Web.Controllers
{
    public class CustomersController : Controller
    {
        private readonly Api.Provider _provider;
        private readonly ILogger _logger;

        private readonly IBraintreeGateway _gateway;
        private readonly EncryptService _encryptService;

        public CustomersController(IServiceProvider services, IHttpClientFactory client)
        {
            _provider = services.GetService<Api.Provider>();
            _encryptService = services.GetService<EncryptService>();

            _gateway = services.GetService<IBraintreeGateway>();
            _logger = services.GetService<ILogger<CustomersController>>();
        }

        // GET: /<controller>/
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Retrieving customer information");



            var customers = JsonConvert.DeserializeObject<List<Customer>>(await _provider.SendGetRequest("customer/All"));

            return View(customers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Customer model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));

            var json = JsonConvert.SerializeObject(model);
            await _provider.SendPostRequest("customer/update", json);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> AddBalance([FromRoute(Name = "id")]Guid customerId, AddBalanceModel balanceModel)
        {

            if (!ModelState.IsValid)
                return View(balanceModel);


            var customer = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));

            var transaction = new TransactionRequest()
            {
                Amount = balanceModel.Amount,
                BillingAddress = new AddressRequest()
                {
                    PostalCode = customer.Address.PostalCode,
                    StreetAddress = customer.Address.FirstLine,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    CountryName = customer.Address.Country,
                    Region = customer.Address.City
                },
                CreditCard = new TransactionCreditCardRequest()
                {
                    CardholderName = $"{customer.FirstName} {customer.LastName}",
                    CVV = balanceModel.Cvv,
                    ExpirationYear = balanceModel.ExpiryYear,
                    ExpirationMonth = balanceModel.ExpiryMonth,
                    Number = balanceModel.CreditCard
                }
            };

            try
            {
                var result = await _gateway.Transaction.SaleAsync(transaction);
                // Validate errors
                if (!result.IsSuccess())
                {
                    ModelState.AddModelError("CreditCard", result.Message);
                    return View(balanceModel);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("CreditCard", "There was an with the payment processor");
                return View(balanceModel);
            }


            // Model to add customer funds
            var model = new AddFundsModel()
            {
                Amount = balanceModel.Amount,
                CreatedOn = DateTime.UtcNow
            };

            // Get the model json and create signature
            var json = JsonConvert.SerializeObject(model);
            var sig = _encryptService.Sign(json);

            // Send the request
            await _provider.SendPostRequest($"customer/AddFunds/{customerId}?sig={HttpUtility.UrlEncode(sig)}", json);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddBalance([FromRoute(Name = "id")]Guid customerId)
        {
            var customer = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));
            ViewData["CustomerName"] = customer.FirstName;
            ViewData["Balance"] = customer.Balance;

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Create(Customer customer)
        {
            customer.CustomerId = Guid.NewGuid();

            var json = JsonConvert.SerializeObject(customer);
            await _provider.SendPostRequest("customer/createnew", json);

            return RedirectToAction(nameof(Index));
        }
    }
}

Distributed-Cw2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project 4o4</title>

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
    WebFont.load({
            google: { "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });</script>

    <link rel="stylesheet" href="~/lib/keen/css/vendors.bundle.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/keen/css/style.bundle.css" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project 4o4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Kelvin Macartney - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- begin::Global Config -->
    <script>
    var KAppOptions = {
            "colors": {
                "brand": "#5c4de5",
                "metal": "#c4c5d6",
                "light": "#ffffff",
                "accent": "#00c5dc",
                "primary": "#5867dd",
                "success": "#34bfa3",
                "info": "#36a3f7",
                "warning": "#ffb822",
                "danger": "#fd3995",
                "focus": "#9816f4"
            }
        };</script>

    <!-- end::Global Config -->

    <script src="~/lib/keen/js/vendors.bundle.js"></script>
    <script src="~/lib/keen/js/scripts.bundle.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>