Distributed-Cw2/Controllers/CustomersController.cs
using Composite;
using Composite.Models.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System.Web;
using Braintree;
using Web.Models;
using Customer = Composite.Data.Customer;
using System.Diagnostics;

namespace Web.Controllers
{
    public class CustomersController : Controller
    {
        private readonly Api.Provider _provider;
        private readonly ILogger _logger;

        private readonly IBraintreeGateway _gateway;
        private readonly EncryptService _encryptService;

        public CustomersController(IServiceProvider services, IHttpClientFactory client)
        {
            _provider = services.GetService<Api.Provider>();
            _encryptService = services.GetService<EncryptService>();

            _gateway = services.GetService<IBraintreeGateway>();
            _logger = services.GetService<ILogger<CustomersController>>();
        }

        // GET: /<controller>/
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Retrieving customer information");



            var customers = JsonConvert.DeserializeObject<List<Customer>>(await _provider.SendGetRequest("customer/All"));

            return View(customers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Customer model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));

            var json = JsonConvert.SerializeObject(model);
            await _provider.SendPostRequest("customer/update", json);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> AddBalance([FromRoute(Name = "id")]Guid customerId, AddBalanceModel balanceModel)
        {

            if (!ModelState.IsValid)
                return View(balanceModel);


            var customer = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));

            var transaction = new TransactionRequest()
            {
                Amount = balanceModel.Amount,
                BillingAddress = new AddressRequest()
                {
                    PostalCode = customer.Address.PostalCode,
                    StreetAddress = customer.Address.FirstLine,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    CountryName = customer.Address.Country,
                    Region = customer.Address.City
                },
                CreditCard = new TransactionCreditCardRequest()
                {
                    CardholderName = $"{customer.FirstName} {customer.LastName}",
                    CVV = balanceModel.Cvv,
                    ExpirationYear = balanceModel.ExpiryYear,
                    ExpirationMonth = balanceModel.ExpiryMonth,
                    Number = balanceModel.CreditCard
                }
            };

            try
            {
                var result = await _gateway.Transaction.SaleAsync(transaction);
                // Validate errors
                if (!result.IsSuccess())
                {
                    ModelState.AddModelError("CreditCard", result.Message);
                    return View(balanceModel);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("CreditCard", "There was an with the payment processor");
                return View(balanceModel);
            }


            // Model to add customer funds
            var model = new AddFundsModel()
            {
                Amount = balanceModel.Amount,
                CreatedOn = DateTime.UtcNow
            };

            // Get the model json and create signature
            var json = JsonConvert.SerializeObject(model);
            var sig = _encryptService.Sign(json);

            // Send the request
            await _provider.SendPostRequest($"customer/AddFunds/{customerId}?sig={HttpUtility.UrlEncode(sig)}", json);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddBalance([FromRoute(Name = "id")]Guid customerId)
        {
            var customer = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));
            ViewData["CustomerName"] = customer.FirstName;
            ViewData["Balance"] = customer.Balance;

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Create(Customer customer)
        {
            customer.CustomerId = Guid.NewGuid();

            var json = JsonConvert.SerializeObject(customer);
            await _provider.SendPostRequest("customer/createnew", json);

            return RedirectToAction(nameof(Index));
        }
    }
}

Distributed-Cw2/Controllers/SendMoneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Composite.Data;
using Composite.Models.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using Web.Models;

namespace Web.Controllers
{
    public class SendMoneyController : Controller
    {
        private readonly Api.Provider _provider;

        public SendMoneyController(IServiceProvider provider)
        {
            _provider = provider.GetService<Api.Provider>();
        }

        [HttpGet]
        public async Task<IActionResult> SendToAccount([FromRoute(Name = "id")] Guid customerId)
        {
            var customers = JsonConvert.DeserializeObject<List<Customer>>(await _provider.SendGetRequest($"customer/All"));

            var thisCustomer = customers.FirstOrDefault(c => c.CustomerId == customerId);

            if (thisCustomer == null)
                throw new NullReferenceException($"Could not find customer with id {customerId}");

            ViewData["SourceCustomer"] = thisCustomer.FirstName;

            // don't let customer send to themselves
            customers = customers.Where(c => c.CustomerId != customerId).ToList();


            // Create the customer select
            ViewData["Customer"] =
                new SelectList(customers, "CustomerId", "FirstName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendToAccount([FromRoute(Name = "id")]Guid customerId, SendMoneyModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var customer = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));

            if (customer.Balance - model.Amount < 0)
            {
                ViewData["SourceCustomer"] = customer.FirstName;

                var customers = JsonConvert.DeserializeObject<List<Customer>>
                    (await _provider.SendGetRequest($"customer/All")).Where(c => c.CustomerId != customerId);

                ViewData["Customer"] =
                    new SelectList(customers, "CustomerId", "FirstName");

                ModelState.AddModelError("Amount", "Insufficient funds");
                return View();
            }

            await _provider.SendPostRequest($"Financial/SendToUser/{customerId}", JsonConvert.SerializeObject(model));

            return RedirectToAction("Index", "Customers");
        }

        [HttpGet]
        public async Task<IActionResult> Withdraw([FromQuery(Name = "Customer")]Guid customerId)
        {
            var customers = JsonConvert.DeserializeObject<List<Customer>>
                (await _provider.SendGetRequest($"customer/All"));

            // Create the customer select
            ViewData["Customer"] =
                new SelectList(customers, "CustomerId", "FirstName", customerId);

            ViewData["CustomerId"] = customerId;

            if (customerId == Guid.Empty)
                return View();

            var financial =
                JsonConvert.DeserializeObject<FinancialInformation>(
                    await _provider.SendGetRequest($"Financial/Get/{customerId}"));

            if (financial == null)
                return View();

            var model = new WithdrawModel()
            {
                Abartn = financial.Abartn,
                AccountName = financial.AccountName,
                AccountNumber = financial.AccountNumber,
                AccountType = financial.AccountType,
                BsbCode = financial.BsbCode,
                IbanNumber = financial.IbanNumber,
                SortCode = financial.SortCode
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> WithDraw([FromForm(Name = "Customer")]Guid customerId, WithdrawModel model)
        {
            var targetCustomer
                = JsonConvert.DeserializeObject<Customer>(await _provider.SendGetRequest($"customer/ById/{customerId}"));

            // Create transferwise customer
            if (targetCustomer.TransferWiseId == 0)
            {
                var finModel = new FinancialInformation()
                {
                    Abartn = model.Abartn,
                    AccountName = model.AccountName,
                    AccountNumber = model.AccountNumber,
                    AccountType = model.AccountType,
                    BsbCode = model.BsbCode,
                    CustomerId = customerId,
                    IbanNumber = model.IbanNumber,
                    SortCode = model.SortCode
                };

                // Create transferwise account
                await _provider.SendPostRequest($"Financial/Create/{customerId}", JsonConvert.SerializeObject(finModel));
            }

            await _provider.SendPostRequest($"Financial/TransferFunds/{customerId}",
                JsonConvert.SerializeObject(new TransferModel()
                {
                    TransferAmount = targetCustomer.Balance,
                    TargetCustomer = targetCustomer.CustomerId,
                    TransferNow = true
                }));

            return RedirectToAction(nameof(WithDraw), new {Customer = customerId});
        }
    }
}

Distributed-Cw2/Views/Customers/AddBalance.cshtml
@model Web.Models.AddBalanceModel
@(ViewData["Title"] = "Topup Page")
<div class="col-lg-6">
    <div class="k-portlet">
        <div class="k-portlet__head">
            <div class="k-portlet__head-label">
                <h3 class="k-portlet__head-title">
                    Add customer balance
                </h3>
            </div>
            <div class="k-portlet__head-toolbar">
                <div class="k-portlet__head-group">
                    <a asp-action="Index" class="btn btn-default btn-sm btn-bold btn-upper">View customers</a>
                </div>
            </div>
        </div>

        <div class="k-portlet__body">
            <form asp-action="AddBalance" asp-antiforgery="true">
                <div class="form-group">
                    <h5>
                        Adding to @ViewData["CustomerName"]'s balance of, £@ViewData["Balance"]
                    </h5>
                </div>

                <div class="form-group ">
                    <label>Add to customer balance</label>
                    <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">£</span></div>
                        <input type="text" asp-for="Amount" class="form-control" placeholder="Add mount">
                    </div>
                    <span class="form-text text-muted">Will add the amount entered to the balance </span>
                    @Html.ValidationMessageFor(e => e.Amount)
                </div>

                <div class="k-separator k-separator--space-lg k-separator--border-dashed"></div>

                <div class="form-group">
                    <h5>
                        Customer Credit Card
                    </h5>
                </div>

                <div class="form-group">
                    <label>Credit card Number</label>
                    <input type="text" asp-for="CreditCard" class="form-control" placeholder="Credit Card">
                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                    @Html.ValidationMessageFor(e => e.CreditCard)
                </div>

                <div class="form-group row">
                    <div class="col-6">
                        <label>CVV</label>
                        <input type="text" asp-for="Cvv" class="form-control" placeholder="CVV">
                    </div>

                    @Html.ValidationMessageFor(e => e.Cvv)
                </div>

                <div class="form-group row">
                    <div class="col-6">
                        <label>Expiry Month</label>
                        <input type="text" asp-for="ExpiryMonth" class="form-control" placeholder="Month">
                    </div>
                    <div class="col-6">
                        <label>Expiry Year</label>
                        <input type="text" asp-for="ExpiryYear" class="form-control" placeholder="Year">
                    </div>

                    @Html.ValidationMessageFor(e => e.ExpiryMonth)
                    @Html.ValidationMessageFor(e => e.ExpiryYear)
                </div>
                <div class="form-group">
                    <span class="form-text text-muted">We use the customers name and address to process the payment</span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-dollar-sign"></i> Add Money</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Distributed-Cw2/Views/Customers/Create.cshtml
@model Composite.Data.Customer

@{
    ViewData["Title"] = "Create Customer Page";

}
<div class="k-portlet">
    <div class="k-portlet__head">
        <div class="k-portlet__head-label">
            <h3 class="k-portlet__head-title">
                <i class="la la-plus"></i>
                Add new customer
            </h3>
        </div>
    </div>
    <div class="k-portlet__body">
        <form asp-action="Create" autocomplete="off" asp-antiforgery="true">
            <div class="form-group row">
                <label class="col-3 col-form-label">First name</label>
                <div class="col-6">
                    <input class="form-control" asp-for="FirstName" placeholder="First Name">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Last name</label>
                <div class="col-6">
                    <input class="form-control" asp-for="LastName" placeholder="Last Name">
                </div>
            </div>

            <div class="row">
                <label class="col-3"></label>
                <div class="col-6">
                    <h3 class="k-section__title k-section__title-sm">Address:</h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Street address</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Address.FirstLine" placeholder="Street Address">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">City</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Address.City" placeholder="City">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">State</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Address.State" placeholder="State">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Country</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Address.Country" placeholder="Country">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Post code</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Address.PostalCode" placeholder="Postcode">
                </div>
            </div>

            <div class="row">
                <label class="col-3"></label>
                <div class="col-6">
                    <h3 class="k-section__title k-section__title-sm">Money:</h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3 col-form-label">Initial balance</label>
                <div class="col-6">
                    <input class="form-control" asp-for="Balance" placeholder="Initial customer balance">
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                </div>
                <div class="col-9">
                    <button type="submit" class="btn btn-success">Add Now</button>
                </div>
            </div>
        </form>

    </div>
</div>

Distributed-Cw2/Views/Customers/Index.cshtml
@using System.Linq
@model List<Composite.Data.Customer>

@{
    ViewData["Title"] = "Customers Page";
}

<div class="k-portlet">
    <div class="k-portlet__head">
        <div class="k-portlet__head-label">
            <h3 class="k-portlet__head-title">Customers</h3>
        </div>

        <div class="k-portlet__head-toolbar">
            <a asp-action="Create" class="btn btn-success btn-upper">Add new</a>
        </div>
    </div>
    <div class="k-portlet__body">
        <div class="accordion accordion-outline" id="Customers">
            @{
                foreach (var customer in Model)
                {
                    <div class="card">
                        <div class="card-header" id="customer-@(customer.CustomerId)">
                            <div class="card-title collapsed" data-toggle="collapse" data-target="#collapse-@(customer.CustomerId)" aria-expanded="false" aria-controls="collapseOne3">
                                @customer.FirstName @customer.LastName, Balance: £@customer.Balance
                            </div>
                        </div>
                        <div id="collapse-@(customer.CustomerId)" class="card-body-wrapper collapse" aria-labelledby="customer-@(customer.CustomerId)" data-parent="#Customers" style="">
                            <div class="card-body">

                                <form asp-action="Update" autocomplete="off" asp-antiforgery="true">
                                    <div class="form-group row">
                                        <span class="col-3"></span>
                                        <div class="col-8">
                                            <a asp-action="AddBalance" asp-route-id="@customer.CustomerId" class="btn btn-lg btn-success">
                                                <i class="la la-plus"></i> Add Balance
                                            </a>
                                            <a asp-controller="SendMoney" asp-action="SendToAccount" asp-route-id="@customer.CustomerId" class="btn btn-lg btn-success">
                                                <i class="la la-dollar"></i> Send Money
                                            </a>
                                            <a asp-controller="SendMoney" asp-action="WithDraw" asp-route-Customer="@customer.CustomerId" class="btn btn-lg btn-success">
                                                <i class="la la-bank"></i> Withdraw
                                            </a>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-6">
                                            <input class="form-control" type="hidden" value="@customer.CustomerId" asp-for="First().CustomerId" placeholder="Enter email">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">First name</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.FirstName" asp-for="First().FirstName" placeholder="Enter email">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">Last name</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.LastName" asp-for="First().LastName" placeholder="Enter email">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <label class="col-3"></label>
                                        <div class="col-6">
                                            <h3 class="k-section__title k-section__title-sm">Address:</h3>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">Street address</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.Address.FirstLine" asp-for="First().Address.FirstLine" placeholder="Street Address">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">City</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.Address.City" asp-for="First().Address.City" placeholder="City">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">State</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.Address.State" asp-for="First().Address.State" placeholder="State">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">Country</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.Address.Country" asp-for="First().Address.Country" placeholder="Country">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-3 col-form-label">Post code</label>
                                        <div class="col-6">
                                            <input class="form-control" value="@customer.Address.PostalCode" asp-for="First().Address.PostalCode" placeholder="Postcode">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-3">
                                        </div>
                                        <div class="col-9">
                                            <button type="submit" class="btn btn-success">Update</button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>